<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <EmbeddedResource Include="Assets\classdata.tpk" LogicalName="classdata.tpk"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AsmResolver.DotNet"/>
        <PackageReference Include="AssetsTools.NET"/>
        <PackageReference Include="AsyncAwaitBestPractices"/>
        <PackageReference Include="Autofac"/>
        <PackageReference Include="CliWrap"/>
        <PackageReference Include="Microsoft.Extensions.Http"/>
        <PackageReference Include="Microsoft.Extensions.Http.Resilience"/>
        <PackageReference Include="NLog"/>
        <PackageReference Include="NLog.Extensions.Logging"/>
        <PackageReference Include="NVorbis"/>
        <PackageReference Include="R3"/>
        <PackageReference Include="Refit"/>
        <PackageReference Include="Refit.HttpClientFactory"/>
        <PackageReference Include="Semver"/>
        <PackageReference Include="SoundFlow"/>
        <PackageReference Include="ValveKeyValue"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Euterpe.Abstractions\Euterpe.Abstractions.csproj"/>
        <ProjectReference Include="..\Euterpe.CodeAnalysis\Euterpe.CodeAnalysis.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\Euterpe.Localization\Euterpe.Localization.csproj"/>
    </ItemGroup>

</Project>