// HintName: PlatformServices.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Euterpe source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


namespace Euterpe.Platform;

internal sealed class PlatformServices : global::Euterpe.IPlatformServices
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.PlatformServicesGenerator", "1.0.0")]
    public static void RegisterServices(global::Autofac.ContainerBuilder builder)
    {
        #pragma warning disable CA1416
        builder.RegisterType<global::Sample.WindowsGamePathDiscovery>().As<global::Euterpe.Abstractions.IGamePathDiscovery>().PropertiesAutowired().InstancePerMatchingLifetimeScope(global::Euterpe.IocContainer.GameScopeTag);
        builder.RegisterType<global::Sample.WindowsLauncher>().As<global::Euterpe.Abstractions.IPlatformLauncher>().PropertiesAutowired().SingleInstance();
        #pragma warning restore CA1416
    }
}
