<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\NativeAot.props"/>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations"/>
        <PackageReference Include="JetBrains.dotCover.Framework"/>
        <PackageReference Include="TUnit"/>
        <PackageReference Include="TUnit.Mocks"/>
        <PackageReference Include="TUnit.Mocks.Http"/>
        <PackageReference Include="TUnit.Mocks.Logging"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Euterpe.Core\Euterpe.Core.csproj"/>
        <ProjectReference Include="..\..\src\Euterpe.Desktop\Euterpe.Desktop.csproj"/>
    </ItemGroup>

    <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
        <ProjectReference Include="..\..\src\Platforms\Euterpe.Windows\Euterpe.Windows.csproj"/>
    </ItemGroup>
    <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
        <ProjectReference Include="..\..\src\Platforms\Euterpe.Linux\Euterpe.Linux.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <Compile Remove="Platforms\Windows\**\*.cs" Condition="!$([MSBuild]::IsOSPlatform('Windows'))"/>
        <Compile Remove="Platforms\Linux\**\*.cs" Condition="!$([MSBuild]::IsOSPlatform('Linux'))"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="Core\Audio\Codecs\Fixtures\Tone.ogg" CopyToOutputDirectory="PreserveNewest" TargetPath="Fixtures\Tone.ogg"/>
    </ItemGroup>

</Project>